'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { AuthBrandHeader } from '@/components/auth-brand-header'

export default function RedefinirSenhaPage() {
  const [token, setToken] = useState<string | null>(null); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => setToken(new URLSearchParams(window.location.search).get('token')), [])
  async function submit(event: FormEvent) { event.preventDefault(); if (!token || password !== confirm) { setMessage(!token ? 'O link é inválido ou expirou.' : 'As senhas não conferem.'); return }; setLoading(true); const response = await fetch('/api/auth/reset-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token, newPassword: password }) }); setLoading(false); setMessage(response.ok ? 'Senha atualizada. Você já pode entrar na G‑LAB.' : 'Não foi possível usar este link. Solicite um novo e-mail.') }
  return <main className="relative isolate flex min-h-svh flex-col items-center justify-center overflow-hidden bg-background px-4 py-10 text-foreground"><div className="premium-grid absolute inset-0 opacity-30" /><div className="relative z-10 flex w-full flex-col items-center"><AuthBrandHeader /><section className="w-full max-w-md rounded-[2rem] border border-border bg-card/95 p-7 shadow-2xl shadow-primary/10 sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Segurança G‑LAB</p><h1 className="mt-4 text-4xl font-black">Nova senha</h1><p className="mt-3 text-sm leading-6 text-slate-400">Crie uma senha forte, com no mínimo oito caracteres.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-bold">Nova senha<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-300" /></label><label className="block text-sm font-bold">Repita a nova senha<input required minLength={8} type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-300" /></label>{message && <p className="rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-slate-300">{message}</p>}<button disabled={loading || !token} className="w-full rounded-xl bg-gradient-to-r from-cyan-300 to-blue-500 px-4 py-3 font-black text-slate-950 disabled:opacity-50">{loading ? 'Atualizando…' : 'Salvar nova senha'}</button></form><Link href="/sign-in" className="mt-7 block text-center text-sm text-cyan-300 hover:text-cyan-200">Voltar para entrar</Link></section></div></main>
}
