'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { AuthBrandHeader } from '@/components/auth-brand-header'

export default function EsqueciSenhaPage() {
  const [email, setEmail] = useState(''); const [state, setState] = useState<'idle' | 'sent' | 'error'>('idle'); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setState('idle'); try { const response = await fetch('/api/auth/request-password-reset', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: email.trim().toLowerCase(), redirectTo: `${window.location.origin}/redefinir-senha` }) }); setState(response.ok ? 'sent' : 'error') } catch { setState('error') } finally { setLoading(false) } }
  return <main className="relative isolate flex min-h-svh flex-col items-center justify-center overflow-hidden bg-background px-4 py-10 text-foreground"><div className="premium-grid absolute inset-0 opacity-30" /><div className="relative z-10 flex w-full flex-col items-center"><AuthBrandHeader /><section className="w-full max-w-md rounded-[2rem] border border-border bg-card/95 p-7 shadow-2xl shadow-primary/10 sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Segurança G‑LAB</p><h1 className="mt-4 text-4xl font-black">Redefinir senha</h1>{state === 'sent' ? <p className="mt-5 rounded-2xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-sm leading-6 text-emerald-100">Se houver uma conta para este e-mail, enviamos um link seguro para criar uma nova senha.</p> : <><p className="mt-3 text-sm leading-6 text-slate-400">Informe seu e-mail. Por segurança, a resposta não revela se ele está cadastrado.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-bold">E-mail<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-300" placeholder="voce@exemplo.com" /></label>{state === 'error' && <p className="text-sm text-red-300">Não foi possível processar agora. Tente novamente.</p>}<button disabled={loading} className="w-full rounded-xl bg-gradient-to-r from-cyan-300 to-blue-500 px-4 py-3 font-black text-slate-950 disabled:opacity-60">{loading ? 'Enviando…' : 'Enviar link seguro'}</button></form></>}<Link href="/sign-in" className="mt-7 block text-center text-sm text-cyan-300 hover:text-cyan-200">Voltar para entrar</Link></section></div></main>
}
