'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { AuthBrandHeader } from '@/components/auth-brand-header'

export default function EsqueciSenhaPage() {
  const [email, setEmail] = useState(''); const [state, setState] = useState<'idle' | 'sent' | 'error'>('idle'); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setState('idle'); const response = await fetch('/api/auth/request-password-reset', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, redirectTo: `${window.location.origin}/redefinir-senha` }) }); setLoading(false); setState(response.ok ? 'sent' : 'error') }
  return <main className="relative isolate flex min-h-svh flex-col items-center justify-center overflow-hidden bg-[#040610] px-4 py-12 text-white"><div className="premium-grid absolute inset-0 opacity-40" /><div className="absolute -left-40 top-0 h-[520px] w-[520px] rounded-full bg-blue-600/[.14] blur-[160px]" /><div className="absolute -right-32 bottom-0 h-[560px] w-[560px] rounded-full bg-violet-600/[.13] blur-[180px]" /><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-cyan-300/50 to-transparent" /><div className="relative z-10 flex w-full flex-col items-center"><AuthBrandHeader /><section className="w-full max-w-md rounded-[28px] border border-white/[.12] bg-[#080b16]/90 p-8 shadow-[0_45px_120px_rgba(0,0,0,.55)] backdrop-blur-xl"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Segurança G‑LAB</p><h1 className="mt-4 text-4xl font-black">Redefinir senha</h1>{state === 'sent' ? <p className="mt-5 rounded-2xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-sm leading-6 text-emerald-100">Se houver uma conta para este e-mail, enviamos um link seguro para criar uma nova senha.</p> : <><p className="mt-3 text-sm leading-6 text-slate-400">Informe seu e-mail. Por segurança, a resposta não revela se ele está cadastrado.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-bold">E-mail<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-300" placeholder="voce@exemplo.com" /></label>{state === 'error' && <p className="text-sm text-red-300">Não foi possível processar agora. Tente novamente.</p>}<button disabled={loading} className="w-full rounded-xl bg-gradient-to-r from-cyan-300 to-blue-500 px-4 py-3 font-black text-slate-950 disabled:opacity-60">{loading ? 'Enviando…' : 'Enviar link seguro'}</button></form></>}<Link href="/sign-in" className="mt-7 block text-center text-sm text-cyan-300 hover:text-cyan-200">Voltar para entrar</Link></section></div></main>
}
