import Image from 'next/image'
import Link from 'next/link'
import { BookOpen, CheckCircle2, ChevronRight, LockKeyhole, Sparkles } from 'lucide-react'
import { currentPlatformUser, studentEnrollments } from '@/lib/learning-platform'

export const dynamic = 'force-dynamic'

export default async function AlunoPage() {
  const user = await currentPlatformUser()
  if (!user) return null
  const enrollments = await studentEnrollments(user.email)
  const firstName = user.name.split(' ')[0]

  return <div className="mx-auto max-w-7xl px-5 py-10 md:px-8 md:py-14">
    <section className="relative overflow-hidden rounded-[32px] border border-cyan-400/20 bg-gradient-to-br from-cyan-500/15 via-blue-600/10 to-violet-500/15 p-7 md:p-11"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-cyan-400/20 blur-3xl" /><div className="relative"><span className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-cyan-200"><Sparkles size={14} /> Seu laboratório de evolução</span><h1 className="mt-5 text-4xl font-black tracking-[-.04em] md:text-6xl">Olá, {firstName}.<br /><span className="text-cyan-300">Vamos para a bancada.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-slate-300 md:text-base">Seu conteúdo, progresso e materiais ficam organizados em um só lugar. O acesso é pessoal e protegido pela sua conta G‑LAB.</p></div></section>
    <section className="mt-12"><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-400">Minha biblioteca</p><h2 className="mt-2 text-2xl font-black md:text-3xl">Formações liberadas</h2></div><span className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-slate-400">{enrollments.length} acesso{enrollments.length === 1 ? '' : 's'}</span></div>
      {enrollments.length === 0 ? <div className="rounded-[28px] border border-dashed border-white/15 bg-white/[.025] px-6 py-16 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl border border-cyan-400/20 bg-cyan-400/10 text-cyan-300"><LockKeyhole size={22} /></span><h3 className="mt-5 text-xl font-black">Sua biblioteca está pronta.</h3><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-slate-400">Quando uma formação for confirmada, ela aparecerá aqui automaticamente com os materiais e o seu progresso.</p><Link href="/cursos" className="mt-7 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-black text-slate-950">Conhecer formações <ChevronRight size={16} /></Link></div> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{enrollments.map((item) => { const progress = item.lessonCount ? Math.round((item.completedCount / item.lessonCount) * 100) : 0; return <Link key={item.enrollmentId} href={`/aluno/${item.slug}`} className="group overflow-hidden rounded-[26px] border border-white/10 bg-[#0a0d19] transition hover:-translate-y-1 hover:border-cyan-400/40"><div className="relative aspect-[16/8] bg-gradient-to-br from-blue-600/40 to-violet-600/30">{item.coverUrl && <Image src={item.coverUrl} alt="" fill className="object-cover opacity-80" />}<div className="absolute inset-0 bg-gradient-to-t from-[#0a0d19] to-transparent" /><span className="absolute left-4 top-4 rounded-full bg-emerald-400/15 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-emerald-300">Acesso ativo</span></div><div className="p-6"><h3 className="text-xl font-black">{item.title}</h3><p className="mt-2 line-clamp-2 text-sm text-slate-400">{item.description}</p><div className="mt-6 flex items-center justify-between text-xs text-slate-400"><span className="flex items-center gap-2"><BookOpen size={15} className="text-cyan-300" />{item.lessonCount} aulas</span><span className="flex items-center gap-1 font-bold text-cyan-300">Continuar <ChevronRight size={15} /></span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-blue-500" style={{ width: `${progress}%` }} /></div><p className="mt-2 text-right text-[10px] font-bold text-slate-500">{progress}% concluído</p></div></Link> })}</div>}</section>
    <p className="mt-12 flex items-center justify-center gap-2 text-center text-xs text-slate-500"><CheckCircle2 size={14} className="text-emerald-400" /> Acesso vinculado ao e-mail da compra e à sua conta G‑LAB.</p>
  </div>
}
